#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store
version:      0.07
version_from: lib/Email/Store.pm
installdirs:  site
requires:
    Class::DBI::DATA::Schema:      0
    Class::DBI:                    0.9
    Time::Piece:                   0
    Mail::Message::Attachment::Stripper: 0
    Email::Simple:                 1
    Mail::ListDetector:            0.3
    Mail::Message:                 0
    DBD::SQLite:                   0
    File::Slurp:                   0
    Module::Pluggable::Ordered:    1
    Module::Pluggable:             1.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
