--- #YAML:1.0
name:                Email-Store
version:             0.255
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::DBI:                    3.0.3
    Class::DBI::DATA::Schema:      0
    DBD::SQLite:                   0
    Email::Address  :              1.8
    Email::Date     :              1.1
    Email::MessageID:              0
    Email::MIME:                   1.8
    Email::Simple:                 1.92
    File::Slurp:                   0
    Mail::ListDetector:            0.31
    MIME::Parser:                  0
    Module::Pluggable:             2.6
    Module::Pluggable::Ordered:    1
    SQL::Translator:               0
    Time::Piece:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
